### ISSUE TITLE
cocaleaf farming not working

### ISSUE THREAD

**Issue by shadybizz** [Gigavat02/qb-drugpickup#1]
I don't receive the item "cocaleaf" after picking, there is no error code in console nor the "item don't excess" notification 
I added all items to shared and inventory. all other farming work perfectly except cocaleaf farming

**Comment by Gigavat02** [comment]
> I don't receive the item "cocaleaf" after picking, there is no error code in console nor the "item don't excess" notification I added all items to shared and inventory. all other farming work perfectly except cocaleaf farming

Thank you for letting me know. I looked in to the code and there was a spelling mistake. I have pushed an updated that fixes than.
