### ISSUE TITLE
Cancelbug

### ISSUE THREAD

**Issue by Capaxx** [Gigavat02/qb-drugpickup#2]
Hi, first of all, thank you for your script. I have a little bug that I can't seem to fix. When I stop harvesting with the 'escape' key, the script crashes and we can no longer harvest afterwards. It no longer offers the action.

**Comment by Gigavat02** [comment]
Thanks for letting me know! I have pushed an updated that fixes that issue.

**Comment by Capaxx** [comment]
Thanks man, I spent 10 hours modifying the script. I removed the field part to leave a single item and harvest directly without despawning on one side, and left your script as a field as well. However, I couldn't fix the problem at all. You're a good guy, thank you again!

**Comment by Gigavat02** [comment]
Glad I could help!
